### ISSUE TITLE
[Bug]: Particles disappear after a few minutes of gameplay

### ISSUE THREAD

**Issue by thiper01** [dr3ams/Life-in-the-village-3#88] opened 2023-10-22 21:08 UTC
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.3

### Describe your issue

As I'm playing, suddenly all particles stop appearing, campfire smoke, block breaking particles, it just stops appearing, I have tried every graphics setting option and reopening the save, but it only comes back to normal after I reopen my game completely, staying normal for a few minutes and then happening all over again.

I tried opening the game in different Forge versions and different Java versions, deleting the profile and creating a new one from scratch.
I'm using 8GB RAM, this issue wasn't happening on previous versions of LITV3.

### Steps to reproduce the issue

Play the game normally and after a few minutes, all particles will stop appearing.

### Additional Information

[latest.log](https://github.com/dr3ams/Life-in-the-village-3/files/13064512/latest.log)

**Comment by DoctorMage** [comment] 2023-10-23 10:30
Forge bug not 100% sure was it like this in 2.2? also pc specs
cpu 
gpu
total ram

**Comment by DoctorMage** [comment] 2023-10-30 11:55
Can you try removing the mod item physics

**Comment by thiper01** [comment] 2023-11-01 07:34
I'll be out for a few days and when I get back I'll test it better but as far as I tested, it works!

**Comment by thiper01** [comment] 2023-11-09 23:52
Unfortunately it didn't work

**Comment by thiper01** [comment] 2023-11-10 00:00
Something even weirder happened, after a while of being with no particles, all of a sudden all the particles that weren't appearing exploded from where my head was positioned, from 40+ hours of gameplay on this version this is the first time something like that happened, after that everything continued the same, no particles.

**Comment by SmolFloofyRedhead** [comment] 2023-11-10 03:37
I've seen this issue since the 1.18 versions. Can confirm that there is a burst of particles that indicates the bug has triggered, and they are usually in a line or cluster, and always block breaking particles. Usually though they spawn offscreen, meaning they just... vanish. The bug is also VERY hard to trigger manually, and it can take anywhere from 10-20 minutes to hours. A couple of times I've left the pack running for hours on end so my friend can join me over Hamachi, and I came back to particles still working fine. What has been tried so far:
Disabling all optimization mods
Disabling ItemPhysic
Disabling an assortment of other mods, such as Paxi, Traveler's Titles, Yung's mods, dynview, Farsight, and Chipped.
Nothing has worked. However I was chatting about this on another server and one guy, who has made packs before, mentioned that of all things the Catalog mod was causing tile entities to not render and some other graphical issues. Going to try disabling that.
Oh, and also of note is the fact that this bug hasn't shown up in ANY other 1.18 or 1.19 pack that I've seen.

**Comment by ExpoTr** [comment] 2023-11-15 11:19
I had the same problem and no matter what I did, I couldn't solve the problem. That's why I stopped playing this mod pack. In mine, first of all, the particles that appeared when the grass was broken were coming out. So I think the FTB ultimine triggers this problem. Because I used the FTB ultimine mod to break the grass and create an empty space. This was the scariest bug I've ever encountered while playing Minecraft.

**Comment by thiper01** [comment] 2023-11-15 23:56
> I had the same problem and no matter what I did, I couldn't solve the problem. That's why I stopped playing this mod pack. In mine, first of all, the particles that appeared when the grass was broken were coming out. So I think the FTB ultimine triggers this problem. Because I used the FTB ultimine mod to break the grass and create an empty space. This was the scariest bug I've ever encountered while playing Minecraft.

In my experience it's not necessarily FTB ultimine that triggers this problem but it may contribute to it happening, in my experience anything that would give the computer a bigger load to process can trigger the problem, for example, I have been able to consistently trigger the problem faster just by teleporting to unloaded chunks far away repeatedly.

**Comment by DoctorMage** [comment] 2023-11-16 13:23
![image](https://github.com/dr3ams/Life-in-the-village-3/assets/85318453/0866c746-bb0f-44d0-9af8-458850f64d68)
Credits to Bassjokey try this

**Comment by SmolFloofyRedhead** [comment] 2023-11-27 08:26
Confirmed it through testing that this works. Something about the way VTweaks challenger mob particles spawn just breaks things after some time. For now, disabling challenger mob particles (NOT the mobs themselves) will have to do until the VTweaks dev fixes this.

**Comment by DoctorMage** [comment] 2023-11-30 18:40
Fixed in 2.5a

**Closed by DoctorMage** 2023-11-30 18:40 UTC
Labels: bug, Mod Bug
